### PR TITLE
Rename without_memo -> without_memoization

### PR DESCRIPTION
**Pull request by katyho**
### Summary
- Rename without_memo -> without_memoization
- Mostly just a find and replace :) 
### Testing
Specs pass

### CODE REVIEW

**Review by donaldong — APPROVED** [review]
Thanks!

**Comment by donaldong** [comment]
Oh! We also need to update some wiki pages for this.

Maybe we should check in the wiki pages into the codebase as well, so it's easier to do those type of refactoring

**Comment by katyho** [comment]
> Oh! We also need to update some wiki pages for this.
> 
> Maybe we should check in the wiki pages into the codebase as well, so it's easier to do those type of refactoring

This would be good! Also to do a more thorough read through of wikis and to polish some of the language. I don't think that Github supports this out of the box though (e.g. you can't make a pull request to edit a wiki..)

**Comment by donaldong** [comment]
Github wiki is also a git repo lol ... I think we can just maintain them in the codebase and force-push to the wiki repo when we want to make changes

**Comment by donaldong** [comment]
https://github.com/chanzuckerberg/redis-memo/pull/86

**Comment by katyho** [comment]
> Github wiki is also a git repo lol ... I think we can just maintain them in the codebase and force-push to the wiki repo when we want to make changes

> https://github.com/chanzuckerberg/redis-memo.wiki.git

The link above returns a 404 for me

What do you mean force-push to the wiki repo? Are we going to automate that somehow, or do contributors need to manually make sure that the wiki is updated after updating the github repo?

**Comment by donaldong** [comment]
Oh that's a 404 for me as well. But it is a legit git repo we can clone from.

> Are we going to automate that somehow, or do contributors need to manually make sure that the wiki is updated after updating the github repo?

I was thinking about making this a manual process, since it's somewhat rare (in #86)
https://github.com/chanzuckerberg/redis-memo/blob/af841a822daa0df31cc78af3e327ae2d1a241ec8/docs/README.md

but it's possible to automate this too! (an interesting idea!)

**Pull request merged**
